packages:
  - .

overrides:
  '@aws-sdk/xml-builder@3.972.4>fast-xml-parser': 5.3.5
  eslint-config-next>eslint-import-resolver-typescript: 4.4.5
  eslint-plugin-barrel-files: 1.0.5
  lodash: 4.18.1

ignoredBuiltDependencies:
  - aws-sdk
  - unrs-resolver
