version: 2.1

orbs:
  node: circleci/node@5.0.2

parameters:
  node_version:
    type: string
    default: '16.15.1-browsers'

commands:
  install_deps:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1-all
          cache-only-lockfile: true
          app-dir: $HOME/repo
          override-ci-command: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: $HOME/repo
    steps:
      - checkout
      - install_deps
      - run: yarn lint:ci
      - run: yarn type-check
      - run: yarn test
